
	<div id="language-container-wrapper">
		<a href="http://labor.ny.gov/immigrants/language-access.shtm">
		<div id="language-phone-wrapper" >
			<div id="phone-big-text">1-888-469-7365</div>
			<div id="phone-small-text">Get Free Language Assistance</div>
			<div id="phone-icon" ></div>
		</div>
		</a>
		<div id ="language-flag-wrapper" >
		</div>
		<div id="language-list-wrapper" class="ux-content-expandable ux-only-one ">
			<ul>
				<li>
					<a href="#" class="ux-expandable">Espa&ntilde;ol (Spanish)</a>
					<div>
						<span>
							Llámenos al 1-888-469-7365 si necesita ayuda gratis en su idioma.
						</span>
					</div>	
				</li>
				<li>
					<a href="#" class="ux-expandable">&#20013;&#25991; (Chinese)</a>
					<div>
						<span>			
							&#35531;&#32102;&#25105;&#20497;&#25171;&#38651;&#35441;&#34399;&#30908; : 1-888-469-7365, &#35201;&#27714;&#20813;&#36027;&#30340;&#35486;&#35328;&#21332;&#21161;&#26381;&#21209;&#12290;
						</span>	
					</div>	
				</li>
				<li>
					<a href="#" class="ux-expandable">Русский (Russian)</a>
					<div>
						<span>
							Чтобы получить бесплатные переводческие услуги, позвоните, пожалуйста, по следующему номеру: 1-888-469-7365
						</span>	
					</div>	
				</li>
				<li>
					<a href="#" class="ux-expandable">Italiano (Italian)</a>
					<div>
						<span>
							Chiamare il 1-888-469-7365 per assistenza linguistica gratuita.
						</span>	
				</div>	
				</li>
				<li>
					<a href="#" class="ux-expandable">Kreyòl ayisyen (Haitian-Creole) </a>
					<div>
						<span>
							Tanpri rele nou nan 1-888-469-7365 pou jwenn sèvis èd gratis nan lang.
						</span>	
					</div>	
				</li>
				<li>
					<a href="#" class="ux-expandable">&#54620;&#44397;&#50612; (Korean)</a>
					<div>
						<span>
							&#51204;&#54868; 1-888-469-7365 &#47196; &#47924;&#47308; &#50616;&#50612; &#51648;&#50896; &#49436;&#48708;&#49828;&#47484; &#50836;&#52397;&#54616;&#49901;&#49884;&#50724;.
						</span>	
					</div>	
				</li>
				<li>
					<a href="#" class="ux-expandable">Polski (Polish)</a>
					<div>
						<span>
							Pod numerem telefonu 1-888-469-7365 otrzymają Państwo bezpłatną pomoc językową.
						</span>	
					</div>	
				</li>
			</ul>
		</div>
		<div id="language-container-bottom">
		</div>	
	</div>
